# Some comments.
[alpha]
    ip = "10.0.0.1"
[alpha.config]
    Ports = [ 8001, 8002 ]
    Location = "Toronto"
    Created = 1987-07-05T05:45:00Z
[beta]
    ip = "10.0.0.2"
    [beta.config]
    Ports = [ 9001, 9002 ]
    Location = "New Jersey"
    Created = 1887-01-05T05:55:00Z