{
 "title": "httplib",
 "tags": [ "ngo" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "App", "query": { "query": "label_values(up, app)" } },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(up{app=\"$App\"}, cluster)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(up{app=\"$App\", cluster=\"$Cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "正确率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(ngo_app_httplib_request_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\", code=~\"2.*|3.*\"}[$__range])) / sum(increase(ngo_app_httplib_request_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总请求数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ngo_app_httplib_request_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(ngo_app_httplib_request_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum by(code) (rate(ngo_app_httplib_request_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "耗时",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(ngo_app_httplib_request_duration_range_sum{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])) / sum(rate(ngo_app_httplib_request_duration_range_count{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "COST"
    }
   ]
  },
  {
   "title": "Url",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(url, method) (rate(ngo_app_httplib_request_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(url, method) (rate(ngo_app_httplib_request_duration_range_sum{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])) / sum by(url, method) (rate(ngo_app_httplib_request_duration_range_count{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, url, method) (rate(ngo_app_httplib_request_duration_range_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, url, method) (rate(ngo_app_httplib_request_duration_range_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, url, method) (rate(ngo_app_httplib_request_duration_range_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}