{
 "title": "microservices",
 "tags": [ "ngo" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "App", "query": { "query": "label_values(up, app)" } },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(up{app=\"$App\"}, cluster)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(up{app=\"$App\", cluster=\"$Cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "正确率（server）",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(ngo_app_rpc_server_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\", code=\"OK\"}[$__range])) / sum(increase(ngo_app_rpc_server_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总请求数（server）",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ngo_app_rpc_server_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "吞吐量（server）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(ngo_app_rpc_server_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum by(code) (rate(ngo_app_rpc_server_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "耗时（server）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(ngo_app_rpc_server_responses_seconds_sum{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])) / sum(rate(ngo_app_rpc_server_responses_seconds_count{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))\n",
     "legendFormat": "COST"
    }
   ]
  },
  {
   "title": "服务（server）",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(ngo_app_rpc_server_responses_seconds_count{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(operation) (rate(ngo_app_rpc_server_responses_seconds_sum{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])) / sum by(operation) (rate(ngo_app_rpc_server_responses_seconds_count{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(ngo_app_rpc_server_responses_seconds_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(ngo_app_rpc_server_responses_seconds_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, operation) (rate(ngo_app_rpc_server_responses_seconds_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "正确率（client）",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(ngo_app_rpc_client_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\", code=\"OK\"}[$__range])) / sum(increase(ngo_app_rpc_client_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总请求数（client）",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ngo_app_rpc_client_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "吞吐量（client）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(ngo_app_rpc_client_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum by(code) (rate(ngo_app_rpc_client_requests_total{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "耗时（client）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(ngo_app_rpc_client_responses_seconds_sum{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])) / sum(rate(ngo_app_rpc_client_responses_seconds_count{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "COST"
    }
   ]
  },
  {
   "title": "服务（client）",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(ngo_app_rpc_client_responses_seconds_count{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(operation) (rate(ngo_app_rpc_client_responses_seconds_sum{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])) / sum by(operation) (rate(ngo_app_rpc_client_responses_seconds_count{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(ngo_app_rpc_client_responses_seconds_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(ngo_app_rpc_client_responses_seconds_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, operation) (rate(ngo_app_rpc_client_responses_seconds_bucket{app=\"$App\", cluster=\"$Cluster\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}