ngo:
  microservices:
    http: # unimplemented
    grpc:
      servers:
        - name: server1
          network: tcp
          addr: ":8080"
          timeout: 30s
          registrarRef: "etcd"
          loggerRef: "fmtLogger"
          enableMetrics: false
          enableTracing: false
          enableLogging: false
          grpcOpts:
          metadata:
            "key1": "value1"
      clients:
        - name: client1
          timeout: 30s
          discoveryRef: "etcd"
          balancerName: "round_robin"
          enabledHealthCheck: false
          loggerRef: "fmtLogger"
          enableMetrics: false
          enableTracing: false
          enableLogging: false
          grpcOpts:
    sd:
      etcds:
        - name: etcd1
          endpoints:
            - 127.0.0.1:2379
          namespace: "microservices"
          ttl: 15s
          loggerRef: "fmtLogger"